### ISSUE TITLE
could I change haploid to diploid

### ISSUE THREAD

**Issue by mictadlo** [dsarov/MGAP---Microbial-Genome-Assembler-Pipeline#2]
Hi,
I found here https://github.com/dsarov/MGAP---Microbial-Genome-Assembler-Pipeline/blob/master/MGAP.sh#L62 that `haploid` is set. Where this information get used and would it be possible to set it `diploid`.

Thank you in advance.

Mic

**Comment by dsarov** [comment]
Hi Mic,

The pipeline exclusively works with haploid organisms. I've never tested or even attempted it with diploid species. I'd give some other assemblers a shot.

Sorry I couldn't be more helpful.

Cheers,

Derek
