### ISSUE TITLE
trimmomatic

### ISSUE THREAD

**Issue by mictadlo** [dsarov/MGAP---Microbial-Genome-Assembler-Pipeline#4]
Hi,
In order to change the `trimmomatic` settings do I have to do it [here](https://github.com/dsarov/MGAP---Microbial-Genome-Assembler-Pipeline/blob/21e61b99e0596f1c424f62a3447636db1d227435/assembler.sh#L68)?

Trimmomatic could improve the assembly bu using the `MAXINFO` settings rather than `SLIDINGWINDOW` as they described in their paper.

Did you try to use MAXINFO setting or to use for example [QuorUM](https://arxiv.org/abs/1307.3515) an error corrector for Illumina reads?

Thank you in advance.

Mic

**Comment by dsarov** [comment]
Hi Mic,

Yes, that is the correct location for trimmomatic settings. I haven't tested QuorUM or MAXINFO. I used to use fastx toolkit but found the handling of read pairing a bit clunky. With the way the pipeline is written it should be straightforward to chop and change the programs it uses as long as you know a bit of bash scripting. Just check the input and output files and make sure the file tests are correct. 

I found that anything more than a very light trim affects read scaffolding negatively. Often even fairly low quality bases are useful information. Light filtering seems to improve assemblies over a larger variety of input data but this step is probably highly dependent on what information you are feeding the pipeline.

Good luck!

Derek
